[project]
name = 'Universal-Law-Consensus-Mechanism'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.physical-law-adjustment-voting]
path = 'contracts/physical-law-adjustment-voting.clar'
clarity_version = 2
epoch = 2.5

[contracts.universal-parameter-optimization]
path = 'contracts/universal-parameter-optimization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
